# Generated by Django 2.2.6 on 2019-11-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filehash', models.CharField(max_length=100)),
                ('filepath', models.TextField()),
                ('cdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
