# Generated by Django 2.2.6 on 2019-11-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_engine', '0002_auto_20191103_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='id',
        ),
        migrations.AlterField(
            model_name='filter',
            name='filehash',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
