# Generated by Django 2.2.6 on 2019-11-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_engine', '0003_auto_20191104_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filter',
            old_name='filepath',
            new_name='idb_filepath',
        ),
        migrations.AddField(
            model_name='filter',
            name='pe_filepath',
            field=models.TextField(null=True),
        ),
    ]
