# Generated by Django 2.2.6 on 2019-11-08 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_engine', '0004_auto_20191105_2102'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Filter',
        ),
    ]
