# Generated by Django 2.2.6 on 2019-11-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Main_engine', '0005_delete_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('filehash', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('idb_filepath', models.TextField()),
                ('pe_filepath', models.TextField(null=True)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
