# Generated by Django 2.2.6 on 2019-11-09 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_engine', '0009_auto_20191109_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pe_info',
            name='imphash',
        ),
        migrations.RemoveField(
            model_name='pe_info',
            name='md5hash',
        ),
        migrations.RemoveField(
            model_name='pe_info',
            name='sha_1',
        ),
        migrations.RemoveField(
            model_name='pe_info',
            name='ssdeephash',
        ),
    ]
