# Generated by Django 2.2.6 on 2019-11-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_engine', '0011_pe_info_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='pe_info',
            name='timenum',
            field=models.BigIntegerField(null=True),
        ),
    ]
