# Generated by Django 2.2.6 on 2019-11-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_engine', '0012_pe_info_timenum'),
    ]

    operations = [
        migrations.AddField(
            model_name='pe_info',
            name='md5',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pe_info',
            name='sha_1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pe_info',
            name='ssdeep',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pe_info',
            name='timestamp',
            field=models.TextField(null=True),
        ),
    ]
