# Generated by Django 2.2.6 on 2019-11-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_engine', '0013_auto_20191111_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='pe_info',
            name='imphash',
            field=models.TextField(null=True),
        ),
    ]
