# Generated by Django 2.2.7 on 2019-11-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_engine', '0015_auto_20191112_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='pe_info',
            name='pdbage',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pe_info',
            name='pdbguid',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pe_info',
            name='pdbname',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pe_info',
            name='pdbpath',
            field=models.TextField(null=True),
        ),
    ]
