# Generated by Django 2.2.6 on 2019-11-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_engine', '0016_auto_20191115_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pe_info',
            name='ContainedSections',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pe_info',
            name='EntryPoint',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pe_info',
            name='pdbage',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pe_info',
            name='timenum',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
