# Generated by Django 2.2.6 on 2019-11-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_engine', '0017_auto_20191118_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pe_info',
            name='ContainedSections',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pe_info',
            name='EntryPoint',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pe_info',
            name='pdbage',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pe_info',
            name='timenum',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
