# Generated by Django 2.2.6 on 2019-12-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_engine', '0020_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='username',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='login',
            name='register_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
