# Generated by Django 2.2.6 on 2019-12-18 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_engine', '0021_auto_20191219_0353'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
