DATA_TRANSFER=["SLDT","MOV","PUSH","POP","XCHG","IN","OUT","XLAT","LEA","LDS","LES","LAHF","SAHF","PUSHF","PUSHA","PUSHFD","PUSHAD","POPF","MOVSX","MOVZX"]
ARIHMETIC=["ADD","SBB","DEC","NEG","CMP","ADC","INC","AAA","DAA","SUB","AAS","DAS","MUL","IMUL","AAM","DIV","IDIV","AAD","CBW","CWD","CWDE"]
LOGIC=["NOT","SHL","SHLD","SAL","SHR","SHRD","SAR","ROL","ROR","RCL","RCR","AND","TEST","OR","XOR"]